<?php
/**
 * Created by IntelliJ IDEA.
 * User: victo
 * Date: 18/02/2018
 * Time: 14:47
 */

namespace App\Agi;


use Symfony\Component\Console\Input\InputArgument;

class Branch extends Base
{
    /**
     * @var \App\Entity\Branch
     */
    private $branch;

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub

        $this->setName('pbx:branch')
            ->setDescription('Agi para Ramal')
            ->addArgument('exten', InputArgument::REQUIRED, 'Numero a ser discado.')
            ->addArgument('type', InputArgument::REQUIRED, 'Numero a ser discado.');
    }

    protected function pre()
    {
        $this->branch = $this->getContainer()->get('doctrine.orm.default_entity_manager')->getRepository(\App\Entity\Branch::class)->find($this->input->getArgument('exten'));
    }

    protected function goto()
    {
        $this->agi->exec('SET', 'GOTO_CONTEXT=');
        $this->agi->exec('SET', 'GOTO_PRIORITY=');
        $this->agi->exec('SET', 'GOTO_EXTEN=');

        if (!$this->input->hasArgument('type')) {
            throw new \Exception('Nao foi encontrado o type do siga-me');
        }

        switch ($this->input->getArgument('type')) {
            case 'ALWAYS':
                $this->checkGoto($this->branch->getAlwaysIn());
                break;
            case 'CHANUNAVAIL':
            case 'CONGESTION':
            case 'BUSY':
            case 'NOANSWER':
            case 'CANCEL':
                $this->checkGoto($this->branch->getBusyIn());
                break;
        }

    }
}