<?php
/**
 * Created by IntelliJ IDEA.
 * User: vmuniz
 * Date: 15/06/17
 * Time: 18:58
 */

namespace  App\Agi;

class CheckExten extends Base {

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('pbx:exten:check')
            ->setDescription('Agi para recuperar para onde será direcionado a ligação');

    }

    protected function pre() {

    }
}