<?php
/**
 * Created by IntelliJ IDEA.
 * User: vmuniz
 * Date: 15/06/17
 * Time: 18:58
 */

namespace App\Agi;

use App\Entity\Incoming;
use Symfony\Component\Console\Input\InputArgument;
use App\Entity\Branch;
use App\Entity\PlanRoute;
use App\Entity\Trunk;

class In extends Base
{
    /**
     * @var Branch
     */
    private $branch;

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub

        $this->setName('pbx:in')
            ->setDescription('Agi para Rota de entrada')
            ->addArgument('exten', InputArgument::REQUIRED, 'Numero a ser discado.');
    }

    protected function pre()
    {
        return true;
    }

    protected function goto()
    {
        $route = $this->input->getArgument('exten');
        $incoming = $this->getContainer()->get('doctrine.orm.default_entity_manager')->getRepository(Incoming::class)->findOneBy(['from' => $route]);

        if (!$incoming instanceof Incoming) {
            $incoming = $this->getContainer()->get('doctrine.orm.default_entity_manager')->getRepository(Incoming::class)->findOneBy(['from' => '*']);
        }

        $context = null;

        $this->checkGoto($incoming->getTo());
    }

}