<?php
/**
 * Created by IntelliJ IDEA.
 * User: victo
 * Date: 04/03/2018
 * Time: 23:30
 */

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/branch")
 */
class CDRController extends \App\Controller\Impl\CDRController
{
    /**
     * @Route(".filter", methods={"POST"})
     */
    public function filterAction(Request $request)
    {
        return parent::filterAction($request); // TODO: Change the autogenerated stub
    }

}