<?php declare(strict_types = 1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180217182546 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE auth_client_sequence INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE department_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE group_number_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE incoming_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mailing_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mailing_contact_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mailing_import_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE plan_route_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE plan_route_item_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE queue_members_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE trunk_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_access_profile_seq INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE branch_permission_id INCREMENT BY 100 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE oauth_access_token (id INT NOT NULL, client_id INT DEFAULT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F7FA86A419EB6921 ON oauth_access_token (client_id)');
        $this->addSql('CREATE INDEX IDX_F7FA86A4A76ED395 ON oauth_access_token (user_id)');
        $this->addSql('CREATE TABLE oauth_client (id INT NOT NULL, name VARCHAR(255) NOT NULL, client_id VARCHAR(255) NOT NULL, secret_id VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE oauth_refresh_token (id INT NOT NULL, client_id INT DEFAULT NULL, user_id INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_55DCF75519EB6921 ON oauth_refresh_token (client_id)');
        $this->addSql('CREATE INDEX IDX_55DCF755A76ED395 ON oauth_refresh_token (user_id)');
        $this->addSql('CREATE TABLE branch (id VARCHAR(40) NOT NULL, user_id INT DEFAULT NULL, plan_route_id INT DEFAULT NULL, voicemail_id INT DEFAULT NULL, sip_peers_id VARCHAR(40) DEFAULT NULL, classname VARCHAR(64) DEFAULT NULL, reference VARCHAR(64) DEFAULT NULL, name VARCHAR(255) NOT NULL, alwaysInClassname VARCHAR(64) DEFAULT NULL, alwaysInReference VARCHAR(64) DEFAULT NULL, alwaysOutClassname VARCHAR(64) DEFAULT NULL, alwaysOutReference VARCHAR(64) DEFAULT NULL, busyInClassname VARCHAR(64) DEFAULT NULL, busyInCeference VARCHAR(64) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BB861B1FA76ED395 ON branch (user_id)');
        $this->addSql('CREATE INDEX IDX_BB861B1F3A89839C ON branch (plan_route_id)');
        $this->addSql('CREATE INDEX IDX_BB861B1FF6820CFE ON branch (voicemail_id)');
        $this->addSql('CREATE INDEX IDX_BB861B1F1645FA2D ON branch (sip_peers_id)');
        $this->addSql('CREATE INDEX IDX_BB861B1F22E7379AE9856189 ON branch (alwaysInClassname, alwaysInReference)');
        $this->addSql('CREATE INDEX IDX_BB861B1F203B7D54EB592B47 ON branch (alwaysOutClassname, alwaysOutReference)');
        $this->addSql('CREATE INDEX IDX_BB861B1F8E681B36FEB11B17 ON branch (busyInClassname, busyInCeference)');
        $this->addSql('CREATE INDEX IDX_BB861B1F65C11F00AEA34913 ON branch (classname, reference)');
        $this->addSql('CREATE TABLE department (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE forward (classname VARCHAR(64) NOT NULL, reference VARCHAR(64) NOT NULL, description VARCHAR(255) DEFAULT NULL, custom VARCHAR(255) DEFAULT NULL, context VARCHAR(255) DEFAULT NULL, PRIMARY KEY(classname, reference))');
        $this->addSql('CREATE TABLE group_number (id INT NOT NULL, name VARCHAR(255) NOT NULL, identify VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE incoming (id INT NOT NULL, classname VARCHAR(64) DEFAULT NULL, reference VARCHAR(64) DEFAULT NULL, name VARCHAR(255) NOT NULL, "from" VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_42EFA38A65C11F00AEA34913 ON incoming (classname, reference)');
        $this->addSql('CREATE TABLE ivr (id VARCHAR(40) NOT NULL, moh VARCHAR(80) DEFAULT NULL, name VARCHAR(255) NOT NULL, max_try INT DEFAULT NULL, timeout INT DEFAULT NULL, audio_welcome VARCHAR(255) DEFAULT NULL, audio_read VARCHAR(255) DEFAULT NULL, max_digit INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7F29E7DD1E421F63 ON ivr (moh)');
        $this->addSql('CREATE TABLE ivr_option (option VARCHAR(255) NOT NULL, ivr_id VARCHAR(40) NOT NULL, classname VARCHAR(64) DEFAULT NULL, reference VARCHAR(64) DEFAULT NULL, PRIMARY KEY(ivr_id, option))');
        $this->addSql('CREATE INDEX IDX_9D6D5333B09D9E6B ON ivr_option (ivr_id)');
        $this->addSql('CREATE INDEX IDX_9D6D533365C11F00AEA34913 ON ivr_option (classname, reference)');
        $this->addSql('CREATE TABLE mailing (id INT NOT NULL, description VARCHAR(255) NOT NULL, forwardClassname VARCHAR(64) DEFAULT NULL, forwardReference VARCHAR(64) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3ED9315E90D7C22E5BB5943D ON mailing (forwardClassname, forwardReference)');
        $this->addSql('CREATE TABLE mailing_contact (id INT NOT NULL, mailing_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, info JSON NOT NULL, phone JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5DB203573931AB76 ON mailing_contact (mailing_id)');
        $this->addSql('COMMENT ON COLUMN mailing_contact.info IS \'(DC2Type:json_array)\'');
        $this->addSql('COMMENT ON COLUMN mailing_contact.phone IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE mailing_import (id INT NOT NULL, mailing_id INT DEFAULT NULL, filename VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4CA0FDC63931AB76 ON mailing_import (mailing_id)');
        $this->addSql('CREATE TABLE plan_route (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE plan_route_item (id INT NOT NULL, plan_route_id INT DEFAULT NULL, group_number_id INT DEFAULT NULL, trunk_id INT DEFAULT NULL, "order" INT NOT NULL, count INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DF331E8D3A89839C ON plan_route_item (plan_route_id)');
        $this->addSql('CREATE INDEX IDX_DF331E8DF01282F1 ON plan_route_item (group_number_id)');
        $this->addSql('CREATE INDEX IDX_DF331E8D3E05B87F ON plan_route_item (trunk_id)');
        $this->addSql('CREATE TABLE alembic_version (version_num VARCHAR(32) NOT NULL, PRIMARY KEY(version_num))');
        $this->addSql('CREATE TABLE cdr (uniqueid VARCHAR(150) NOT NULL, sequence INT NOT NULL, accountcode VARCHAR(80) DEFAULT NULL, src VARCHAR(80) DEFAULT NULL, dst VARCHAR(80) DEFAULT NULL, dcontext VARCHAR(80) DEFAULT NULL, clid VARCHAR(80) DEFAULT NULL, channel VARCHAR(80) DEFAULT NULL, dstchannel VARCHAR(80) DEFAULT NULL, lastapp VARCHAR(80) DEFAULT NULL, lastdata VARCHAR(80) DEFAULT NULL, start TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, answer TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, "end" TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duration INT DEFAULT NULL, billsec INT DEFAULT NULL, disposition VARCHAR(45) DEFAULT NULL, amaflags VARCHAR(45) DEFAULT NULL, userfield VARCHAR(256) DEFAULT NULL, linkedid VARCHAR(150) DEFAULT NULL, peeraccount VARCHAR(80) DEFAULT NULL, monitor VARCHAR(255) DEFAULT NULL, PRIMARY KEY(uniqueid, sequence))');
        $this->addSql('CREATE TABLE extensions (id BIGINT NOT NULL, context VARCHAR(40) NOT NULL, exten VARCHAR(40) NOT NULL, priority INT NOT NULL, app VARCHAR(40) NOT NULL, appdata VARCHAR(256) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX extensions_context_exten_priority_key ON extensions (context, exten, priority)');
        $this->addSql('CREATE TABLE iaxfriends (id INT NOT NULL, type VARCHAR(255) DEFAULT NULL, sendani VARCHAR(255) DEFAULT NULL, trunk VARCHAR(255) DEFAULT NULL, requirecalltoken VARCHAR(255) DEFAULT NULL, encryption VARCHAR(255) DEFAULT NULL, transfer VARCHAR(255) DEFAULT NULL, jitterbuffer VARCHAR(255) DEFAULT NULL, forcejitterbuffer VARCHAR(255) DEFAULT NULL, qualifysmoothing VARCHAR(255) DEFAULT NULL, adsi VARCHAR(255) DEFAULT NULL, name VARCHAR(40) NOT NULL, username VARCHAR(40) DEFAULT NULL, mailbox VARCHAR(40) DEFAULT NULL, secret VARCHAR(40) DEFAULT NULL, dbsecret VARCHAR(40) DEFAULT NULL, context VARCHAR(40) DEFAULT NULL, regcontext VARCHAR(40) DEFAULT NULL, host VARCHAR(40) DEFAULT NULL, ipaddr VARCHAR(40) DEFAULT NULL, port INT DEFAULT NULL, defaultip VARCHAR(20) DEFAULT NULL, sourceaddress VARCHAR(20) DEFAULT NULL, mask VARCHAR(20) DEFAULT NULL, regexten VARCHAR(40) DEFAULT NULL, regseconds INT DEFAULT NULL, accountcode VARCHAR(80) DEFAULT NULL, mohinterpret VARCHAR(20) DEFAULT NULL, mohsuggest VARCHAR(20) DEFAULT NULL, inkeys VARCHAR(40) DEFAULT NULL, outkeys VARCHAR(40) DEFAULT NULL, language VARCHAR(10) DEFAULT NULL, callerid VARCHAR(100) DEFAULT NULL, cid_number VARCHAR(40) DEFAULT NULL, fullname VARCHAR(40) DEFAULT NULL, auth VARCHAR(20) DEFAULT NULL, maxauthreq INT DEFAULT NULL, disallow VARCHAR(200) DEFAULT NULL, allow VARCHAR(200) DEFAULT NULL, codecpriority VARCHAR(40) DEFAULT NULL, qualify VARCHAR(10) DEFAULT NULL, qualifyfreqok VARCHAR(10) DEFAULT NULL, qualifyfreqnotok VARCHAR(10) DEFAULT NULL, timezone VARCHAR(20) DEFAULT NULL, amaflags VARCHAR(20) DEFAULT NULL, setvar VARCHAR(200) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4657F7198CDE5729 ON iaxfriends (type)');
        $this->addSql('CREATE INDEX IDX_4657F719C961C9B ON iaxfriends (sendani)');
        $this->addSql('CREATE INDEX IDX_4657F71978628D47 ON iaxfriends (trunk)');
        $this->addSql('CREATE INDEX IDX_4657F719E29E6BAE ON iaxfriends (requirecalltoken)');
        $this->addSql('CREATE INDEX IDX_4657F7195BBDDBBB ON iaxfriends (encryption)');
        $this->addSql('CREATE INDEX IDX_4657F7194034A3C0 ON iaxfriends (transfer)');
        $this->addSql('CREATE INDEX IDX_4657F719A3A0630C ON iaxfriends (jitterbuffer)');
        $this->addSql('CREATE INDEX IDX_4657F7193F5AF6E7 ON iaxfriends (forcejitterbuffer)');
        $this->addSql('CREATE INDEX IDX_4657F719B1C1B4D7 ON iaxfriends (qualifysmoothing)');
        $this->addSql('CREATE INDEX IDX_4657F719DD7CDF4F ON iaxfriends (adsi)');
        $this->addSql('CREATE INDEX iaxfriends_name_host ON iaxfriends (name, host)');
        $this->addSql('CREATE INDEX iaxfriends_name_ipaddr_port ON iaxfriends (name, ipaddr, port)');
        $this->addSql('CREATE INDEX iaxfriends_host_port ON iaxfriends (host, port)');
        $this->addSql('CREATE INDEX iaxfriends_ipaddr_port ON iaxfriends (ipaddr, port)');
        $this->addSql('CREATE UNIQUE INDEX iaxfriends_name_key ON iaxfriends (name)');
        $this->addSql('CREATE TABLE meetme (bookid INT NOT NULL, confno VARCHAR(80) NOT NULL, starttime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, endtime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pin VARCHAR(20) DEFAULT NULL, adminpin VARCHAR(20) DEFAULT NULL, opts VARCHAR(20) DEFAULT NULL, adminopts VARCHAR(20) DEFAULT NULL, recordingfilename VARCHAR(80) DEFAULT NULL, recordingformat VARCHAR(10) DEFAULT NULL, maxusers INT DEFAULT NULL, members INT NOT NULL, PRIMARY KEY(bookid))');
        $this->addSql('CREATE INDEX meetme_confno_start_end ON meetme (confno, starttime, endtime)');
        $this->addSql('CREATE TABLE musiconhold (name VARCHAR(80) NOT NULL, mode VARCHAR(255) DEFAULT NULL, directory VARCHAR(255) DEFAULT NULL, application VARCHAR(255) DEFAULT NULL, digit VARCHAR(1) DEFAULT NULL, sort VARCHAR(10) DEFAULT NULL, format VARCHAR(10) DEFAULT NULL, stamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE INDEX IDX_BD5D904F97CA47AB ON musiconhold (mode)');
        $this->addSql('CREATE TABLE queues (name VARCHAR(128) NOT NULL, ringinuse VARCHAR(255) DEFAULT NULL, setinterfacevar VARCHAR(255) DEFAULT NULL, setqueuevar VARCHAR(255) DEFAULT NULL, setqueueentryvar VARCHAR(255) DEFAULT NULL, announce_to_first_user VARCHAR(255) DEFAULT NULL, relative_periodic_announce VARCHAR(255) DEFAULT NULL, random_periodic_announce VARCHAR(255) DEFAULT NULL, autofill VARCHAR(255) DEFAULT NULL, autopause VARCHAR(255) DEFAULT NULL, autopausebusy VARCHAR(255) DEFAULT NULL, autopauseunavail VARCHAR(255) DEFAULT NULL, strategy VARCHAR(255) DEFAULT NULL, reportholdtime VARCHAR(255) DEFAULT NULL, timeoutrestart VARCHAR(255) DEFAULT NULL, description VARCHAR(128) DEFAULT NULL, musiconhold VARCHAR(128) DEFAULT NULL, announce VARCHAR(128) DEFAULT NULL, context VARCHAR(128) DEFAULT NULL, timeout INT DEFAULT NULL, monitor_format VARCHAR(8) DEFAULT NULL, membermacro VARCHAR(512) DEFAULT NULL, membergosub VARCHAR(512) DEFAULT NULL, queue_youarenext VARCHAR(128) DEFAULT NULL, queue_thereare VARCHAR(128) DEFAULT NULL, queue_callswaiting VARCHAR(128) DEFAULT NULL, queue_quantity1 VARCHAR(128) DEFAULT NULL, queue_quantity2 VARCHAR(128) DEFAULT NULL, queue_holdtime VARCHAR(128) DEFAULT NULL, queue_minutes VARCHAR(128) DEFAULT NULL, queue_minute VARCHAR(128) DEFAULT NULL, queue_seconds VARCHAR(128) DEFAULT NULL, queue_thankyou VARCHAR(128) DEFAULT NULL, queue_callerannounce VARCHAR(128) DEFAULT NULL, queue_reporthold VARCHAR(128) DEFAULT NULL, announce_frequency INT DEFAULT NULL, min_announce_frequency INT DEFAULT NULL, announce_round_seconds INT DEFAULT NULL, announce_holdtime VARCHAR(128) DEFAULT NULL, announce_position VARCHAR(128) DEFAULT NULL, announce_position_limit INT DEFAULT NULL, periodic_announce VARCHAR(50) DEFAULT NULL, periodic_announce_frequency INT DEFAULT NULL, retry INT DEFAULT NULL, wrapuptime INT DEFAULT NULL, penaltymemberslimit INT DEFAULT NULL, monitor_type VARCHAR(128) DEFAULT NULL, autopausedelay INT DEFAULT NULL, maxlen INT DEFAULT NULL, servicelevel INT DEFAULT NULL, joinempty VARCHAR(128) DEFAULT NULL, leavewhenempty VARCHAR(128) DEFAULT NULL, memberdelay INT DEFAULT NULL, weight INT DEFAULT NULL, defaultrule VARCHAR(128) DEFAULT NULL, timeoutpriority VARCHAR(128) DEFAULT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE INDEX IDX_CFCA02961DABCC62 ON queues (ringinuse)');
        $this->addSql('CREATE INDEX IDX_CFCA0296698E29BF ON queues (setinterfacevar)');
        $this->addSql('CREATE INDEX IDX_CFCA0296BF0E1E02 ON queues (setqueuevar)');
        $this->addSql('CREATE INDEX IDX_CFCA0296B076BC3D ON queues (setqueueentryvar)');
        $this->addSql('CREATE INDEX IDX_CFCA0296E039DF6 ON queues (announce_to_first_user)');
        $this->addSql('CREATE INDEX IDX_CFCA029675DFBA15 ON queues (relative_periodic_announce)');
        $this->addSql('CREATE INDEX IDX_CFCA029642656747 ON queues (random_periodic_announce)');
        $this->addSql('CREATE INDEX IDX_CFCA029698E57E23 ON queues (autofill)');
        $this->addSql('CREATE INDEX IDX_CFCA0296B99C32FA ON queues (autopause)');
        $this->addSql('CREATE INDEX IDX_CFCA02966EE7A081 ON queues (autopausebusy)');
        $this->addSql('CREATE INDEX IDX_CFCA0296BFDABBDF ON queues (autopauseunavail)');
        $this->addSql('CREATE INDEX IDX_CFCA0296144645ED ON queues (strategy)');
        $this->addSql('CREATE INDEX IDX_CFCA029652579DE3 ON queues (reportholdtime)');
        $this->addSql('CREATE INDEX IDX_CFCA0296F43779C7 ON queues (timeoutrestart)');
        $this->addSql('CREATE TABLE queue_log (time VARCHAR(26) NOT NULL, callid VARCHAR(255) DEFAULT NULL, queuename VARCHAR(255) DEFAULT NULL, agent VARCHAR(255) DEFAULT NULL, event VARCHAR(255) DEFAULT NULL, data VARCHAR(255) DEFAULT NULL, data1 VARCHAR(255) DEFAULT NULL, data2 VARCHAR(255) DEFAULT NULL, data3 VARCHAR(255) DEFAULT NULL, data4 VARCHAR(255) DEFAULT NULL, data5 VARCHAR(255) DEFAULT NULL, PRIMARY KEY(time))');
        $this->addSql('CREATE TABLE queue_member (id INT NOT NULL, queue VARCHAR(128) DEFAULT NULL, branch VARCHAR(40) DEFAULT NULL, "user" INT DEFAULT NULL, penalty INT NOT NULL, paused BOOLEAN NOT NULL, discr VARCHAR(255) NOT NULL, logged BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4A05D0B17FFD7F63 ON queue_member (queue)');
        $this->addSql('CREATE INDEX IDX_4A05D0B1BB861B1F ON queue_member (branch)');
        $this->addSql('CREATE INDEX IDX_4A05D0B18D93D649 ON queue_member ("user")');
        $this->addSql('CREATE TABLE queue_rules (id INT NOT NULL, rule_name VARCHAR(80) NOT NULL, time VARCHAR(32) NOT NULL, min_penalty VARCHAR(32) NOT NULL, max_penalty VARCHAR(32) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE abstract_protocol (id VARCHAR(40) NOT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sippeers (id VARCHAR(40) NOT NULL, type VARCHAR(255) DEFAULT NULL, transport VARCHAR(255) DEFAULT NULL, dtmfmode VARCHAR(255) DEFAULT NULL, directmedia VARCHAR(255) DEFAULT NULL, nat VARCHAR(255) DEFAULT NULL, trustrpid VARCHAR(255) DEFAULT NULL, progressinband VARCHAR(255) DEFAULT NULL, promiscredir VARCHAR(255) DEFAULT NULL, useclientcode VARCHAR(255) DEFAULT NULL, callcounter VARCHAR(255) DEFAULT NULL, allowoverlap VARCHAR(255) DEFAULT NULL, allowsubscribe VARCHAR(255) DEFAULT NULL, videosupport VARCHAR(255) DEFAULT NULL, rfc2833compensate VARCHAR(255) DEFAULT NULL, sendrpid VARCHAR(255) DEFAULT NULL, registertrying VARCHAR(255) DEFAULT NULL, constantssrc VARCHAR(255) DEFAULT NULL, usereqphone VARCHAR(255) DEFAULT NULL, textsupport VARCHAR(255) DEFAULT NULL, faxdetect VARCHAR(255) DEFAULT NULL, buggymwi VARCHAR(255) DEFAULT NULL, sip_callingpres_values VARCHAR(255) DEFAULT NULL, hasvoicemail VARCHAR(255) DEFAULT NULL, subscribemwi VARCHAR(255) DEFAULT NULL, autoframing VARCHAR(255) DEFAULT NULL, g726nonstandard VARCHAR(255) DEFAULT NULL, ignoresdpversion VARCHAR(255) DEFAULT NULL, allowtransfer VARCHAR(255) DEFAULT NULL, dynamic VARCHAR(255) DEFAULT NULL, name VARCHAR(40) NOT NULL, ipaddr VARCHAR(45) DEFAULT NULL, port INT DEFAULT NULL, regseconds INT DEFAULT NULL, defaultuser VARCHAR(40) DEFAULT NULL, fullcontact VARCHAR(80) DEFAULT NULL, regserver VARCHAR(20) DEFAULT NULL, useragent VARCHAR(255) DEFAULT NULL, lastms INT DEFAULT NULL, host VARCHAR(40) DEFAULT NULL, context VARCHAR(40) DEFAULT NULL, permit VARCHAR(95) DEFAULT NULL, deny VARCHAR(95) DEFAULT NULL, secret VARCHAR(40) DEFAULT NULL, md5secret VARCHAR(40) DEFAULT NULL, remotesecret VARCHAR(40) DEFAULT NULL, callgroup VARCHAR(40) DEFAULT NULL, pickupgroup VARCHAR(40) DEFAULT NULL, language VARCHAR(40) DEFAULT NULL, disallow VARCHAR(200) DEFAULT NULL, allow VARCHAR(200) DEFAULT NULL, insecure VARCHAR(40) DEFAULT NULL, accountcode VARCHAR(80) DEFAULT NULL, setvar VARCHAR(200) DEFAULT NULL, callerid VARCHAR(40) DEFAULT NULL, amaflags VARCHAR(40) DEFAULT NULL, busylevel INT DEFAULT NULL, maxcallbitrate INT DEFAULT NULL, mailbox VARCHAR(40) DEFAULT NULL, "session-expires" INT DEFAULT NULL, "session-minse" INT DEFAULT NULL, t38pt_usertpsource VARCHAR(40) DEFAULT NULL, regexten VARCHAR(40) DEFAULT NULL, fromdomain VARCHAR(40) DEFAULT NULL, fromuser VARCHAR(40) DEFAULT NULL, qualify VARCHAR(40) DEFAULT NULL, defaultip VARCHAR(45) DEFAULT NULL, rtptimeout INT DEFAULT NULL, rtpholdtimeout INT DEFAULT NULL, outboundproxy VARCHAR(40) DEFAULT NULL, callbackextension VARCHAR(40) DEFAULT NULL, timert1 INT DEFAULT NULL, timerb INT DEFAULT NULL, qualifyfreq INT DEFAULT NULL, contactpermit VARCHAR(95) DEFAULT NULL, contactdeny VARCHAR(95) DEFAULT NULL, auth VARCHAR(40) DEFAULT NULL, fullname VARCHAR(40) DEFAULT NULL, trunkname VARCHAR(40) DEFAULT NULL, cid_number VARCHAR(40) DEFAULT NULL, mohinterpret VARCHAR(40) DEFAULT NULL, mohsuggest VARCHAR(40) DEFAULT NULL, parkinglot VARCHAR(40) DEFAULT NULL, vmexten VARCHAR(40) DEFAULT NULL, rtpkeepalive INT DEFAULT NULL, "call-limit" INT DEFAULT NULL, "session-timers" VARCHAR(255) DEFAULT NULL, "session-refresher" VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3DC2982A8CDE5729 ON sippeers (type)');
        $this->addSql('CREATE INDEX IDX_3DC2982A66AB212E ON sippeers (transport)');
        $this->addSql('CREATE INDEX IDX_3DC2982A3D3283CE ON sippeers (dtmfmode)');
        $this->addSql('CREATE INDEX IDX_3DC2982A66C571DE ON sippeers (directmedia)');
        $this->addSql('CREATE INDEX IDX_3DC2982A9686D0FB ON sippeers (nat)');
        $this->addSql('CREATE INDEX IDX_3DC2982AF1A0A39E ON sippeers (trustrpid)');
        $this->addSql('CREATE INDEX IDX_3DC2982AB920544D ON sippeers (progressinband)');
        $this->addSql('CREATE INDEX IDX_3DC2982A22558EE9 ON sippeers (promiscredir)');
        $this->addSql('CREATE INDEX IDX_3DC2982A24A832DB ON sippeers (useclientcode)');
        $this->addSql('CREATE INDEX IDX_3DC2982AFDC9A2D9 ON sippeers (callcounter)');
        $this->addSql('CREATE INDEX IDX_3DC2982A21378B91 ON sippeers (allowoverlap)');
        $this->addSql('CREATE INDEX IDX_3DC2982A2071E23B ON sippeers (allowsubscribe)');
        $this->addSql('CREATE INDEX IDX_3DC2982A4160ACEB ON sippeers (videosupport)');
        $this->addSql('CREATE INDEX IDX_3DC2982AA3AA5780 ON sippeers (rfc2833compensate)');
        $this->addSql('CREATE INDEX IDX_3DC2982A16B714ED ON sippeers ("session-timers")');
        $this->addSql('CREATE INDEX IDX_3DC2982A5DE68FE9 ON sippeers ("session-refresher")');
        $this->addSql('CREATE INDEX IDX_3DC2982AAB18E017 ON sippeers (sendrpid)');
        $this->addSql('CREATE INDEX IDX_3DC2982A87C0D8D4 ON sippeers (registertrying)');
        $this->addSql('CREATE INDEX IDX_3DC2982A3CCDD349 ON sippeers (constantssrc)');
        $this->addSql('CREATE INDEX IDX_3DC2982A9A90FE26 ON sippeers (usereqphone)');
        $this->addSql('CREATE INDEX IDX_3DC2982A6CBB95D5 ON sippeers (textsupport)');
        $this->addSql('CREATE INDEX IDX_3DC2982A7BF8D4D9 ON sippeers (faxdetect)');
        $this->addSql('CREATE INDEX IDX_3DC2982A75779234 ON sippeers (buggymwi)');
        $this->addSql('CREATE INDEX IDX_3DC2982AFDDE2612 ON sippeers (sip_callingpres_values)');
        $this->addSql('CREATE INDEX IDX_3DC2982AE2235C19 ON sippeers (hasvoicemail)');
        $this->addSql('CREATE INDEX IDX_3DC2982A4A3535ED ON sippeers (subscribemwi)');
        $this->addSql('CREATE INDEX IDX_3DC2982AE205704D ON sippeers (autoframing)');
        $this->addSql('CREATE INDEX IDX_3DC2982A9FFCDCF1 ON sippeers (g726nonstandard)');
        $this->addSql('CREATE INDEX IDX_3DC2982AC4580138 ON sippeers (ignoresdpversion)');
        $this->addSql('CREATE INDEX IDX_3DC2982A3ABFED67 ON sippeers (allowtransfer)');
        $this->addSql('CREATE INDEX IDX_3DC2982A4BAB0AB4 ON sippeers (dynamic)');
        $this->addSql('CREATE INDEX sippeers_name_host ON sippeers (name, host)');
        $this->addSql('CREATE INDEX sippeers_host_port ON sippeers (host, port)');
        $this->addSql('CREATE INDEX sippeers_ipaddr_port ON sippeers (ipaddr, port)');
        $this->addSql('CREATE UNIQUE INDEX sippeers_name_key ON sippeers (name)');
        $this->addSql('CREATE TABLE voicemail (uniqueid INT NOT NULL, attach VARCHAR(255) DEFAULT NULL, deletevoicemail VARCHAR(255) DEFAULT NULL, saycid VARCHAR(255) DEFAULT NULL, sendvoicemail VARCHAR(255) DEFAULT NULL, review VARCHAR(255) DEFAULT NULL, tempgreetwarn VARCHAR(255) DEFAULT NULL, operator VARCHAR(255) DEFAULT NULL, envelope VARCHAR(255) DEFAULT NULL, forcename VARCHAR(255) DEFAULT NULL, forcegreetings VARCHAR(255) DEFAULT NULL, context VARCHAR(80) NOT NULL, mailbox VARCHAR(80) NOT NULL, password VARCHAR(80) NOT NULL, fullname VARCHAR(80) DEFAULT NULL, alias VARCHAR(80) DEFAULT NULL, email VARCHAR(80) DEFAULT NULL, pager VARCHAR(80) DEFAULT NULL, attachfmt VARCHAR(10) DEFAULT NULL, serveremail VARCHAR(80) DEFAULT NULL, language VARCHAR(20) DEFAULT NULL, tz VARCHAR(30) DEFAULT NULL, sayduration INT DEFAULT NULL, callback VARCHAR(80) DEFAULT NULL, dialout VARCHAR(80) DEFAULT NULL, exitcontext VARCHAR(80) DEFAULT NULL, maxmsg INT DEFAULT NULL, volgain NUMERIC(5, 2) DEFAULT NULL, imapuser VARCHAR(80) DEFAULT NULL, imappassword VARCHAR(80) DEFAULT NULL, imapserver VARCHAR(80) DEFAULT NULL, imapport VARCHAR(8) DEFAULT NULL, imapflags VARCHAR(80) DEFAULT NULL, stamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(uniqueid))');
        $this->addSql('CREATE INDEX IDX_DD85E34DDEC97C81 ON voicemail (attach)');
        $this->addSql('CREATE INDEX IDX_DD85E34D71EEA338 ON voicemail (deletevoicemail)');
        $this->addSql('CREATE INDEX IDX_DD85E34D3A606FF1 ON voicemail (saycid)');
        $this->addSql('CREATE INDEX IDX_DD85E34D5999A307 ON voicemail (sendvoicemail)');
        $this->addSql('CREATE INDEX IDX_DD85E34D794381C6 ON voicemail (review)');
        $this->addSql('CREATE INDEX IDX_DD85E34DFBADBA12 ON voicemail (tempgreetwarn)');
        $this->addSql('CREATE INDEX IDX_DD85E34DD7A6A781 ON voicemail (operator)');
        $this->addSql('CREATE INDEX IDX_DD85E34D8A957868 ON voicemail (envelope)');
        $this->addSql('CREATE INDEX IDX_DD85E34D1B99BB46 ON voicemail (forcename)');
        $this->addSql('CREATE INDEX IDX_DD85E34D6EBD034 ON voicemail (forcegreetings)');
        $this->addSql('CREATE INDEX voicemail_imapuser ON voicemail (imapuser)');
        $this->addSql('CREATE INDEX voicemail_mailbox_context ON voicemail (mailbox, context)');
        $this->addSql('CREATE INDEX voicemail_mailbox ON voicemail (mailbox)');
        $this->addSql('CREATE INDEX voicemail_context ON voicemail (context)');
        $this->addSql('CREATE TABLE voicemail_messages (dir VARCHAR(255) NOT NULL, msgnum INT NOT NULL, context VARCHAR(80) DEFAULT NULL, macrocontext VARCHAR(80) DEFAULT NULL, callerid VARCHAR(80) DEFAULT NULL, origtime INT DEFAULT NULL, duration INT DEFAULT NULL, recording BYTEA DEFAULT NULL, flag VARCHAR(30) DEFAULT NULL, category VARCHAR(30) DEFAULT NULL, mailboxuser VARCHAR(30) DEFAULT NULL, mailboxcontext VARCHAR(30) DEFAULT NULL, msg_id VARCHAR(40) DEFAULT NULL, PRIMARY KEY(dir, msgnum))');
        $this->addSql('CREATE INDEX voicemail_messages_dir ON voicemail_messages (dir)');
        $this->addSql('CREATE TABLE trunk (id INT NOT NULL, register_type VARCHAR(255) DEFAULT NULL, dial_type VARCHAR(255) DEFAULT NULL, protocol_id VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, ddi VARCHAR(255) DEFAULT NULL, ddd VARCHAR(255) DEFAULT NULL, operator_code VARCHAR(255) DEFAULT NULL, dial_prefix VARCHAR(255) DEFAULT NULL, dial_sufix VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_78628D4758B94789 ON trunk (register_type)');
        $this->addSql('CREATE INDEX IDX_78628D476D0C27C9 ON trunk (dial_type)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_78628D47CCD59258 ON trunk (protocol_id)');
        $this->addSql('CREATE TABLE type_iax_encryption (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_iax_require_calltoken (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_iax_transfer (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_sip_moh_mode (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_profile_sip (name VARCHAR(255) NOT NULL, profile JSON NOT NULL, PRIMARY KEY(name))');
        $this->addSql('COMMENT ON COLUMN type_profile_sip.profile IS \'(DC2Type:json_array)\'');
        $this->addSql('CREATE TABLE type_queue_auto_pause (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_queue_strategy (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_sip_calling_pres (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_sip_direct_media (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_sip_dtmf_mode (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_sip_nat (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_sip_progress_in_band (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_sip_session_refresher (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_sip_session_timers (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_sip_transport (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_type (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE type_yes_no (name VARCHAR(255) NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE users (id INT NOT NULL, user_access_profile_id INT DEFAULT NULL, department_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, avatar VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1483A5E91EDB3112 ON users (user_access_profile_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E9AE80F5DF ON users (department_id)');
        $this->addSql('CREATE TABLE user_access_profile (id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE trunk_register_type (name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, protocol VARCHAR(255) NOT NULL, mask VARCHAR(255) DEFAULT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE TABLE khomp (id VARCHAR(40) NOT NULL, group_id VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE trunk_dial_type (value VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(value))');
        $this->addSql('ALTER TABLE oauth_access_token ADD CONSTRAINT FK_F7FA86A419EB6921 FOREIGN KEY (client_id) REFERENCES oauth_client (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE oauth_access_token ADD CONSTRAINT FK_F7FA86A4A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE oauth_refresh_token ADD CONSTRAINT FK_55DCF75519EB6921 FOREIGN KEY (client_id) REFERENCES oauth_client (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE oauth_refresh_token ADD CONSTRAINT FK_55DCF755A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F3A89839C FOREIGN KEY (plan_route_id) REFERENCES plan_route (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1FF6820CFE FOREIGN KEY (voicemail_id) REFERENCES voicemail (uniqueid) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F1645FA2D FOREIGN KEY (sip_peers_id) REFERENCES sippeers (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F22E7379AE9856189 FOREIGN KEY (alwaysInClassname, alwaysInReference) REFERENCES forward (classname, reference) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F203B7D54EB592B47 FOREIGN KEY (alwaysOutClassname, alwaysOutReference) REFERENCES forward (classname, reference) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F8E681B36FEB11B17 FOREIGN KEY (busyInClassname, busyInCeference) REFERENCES forward (classname, reference) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE branch ADD CONSTRAINT FK_BB861B1F65C11F00AEA34913 FOREIGN KEY (classname, reference) REFERENCES forward (classname, reference) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE incoming ADD CONSTRAINT FK_42EFA38A65C11F00AEA34913 FOREIGN KEY (classname, reference) REFERENCES forward (classname, reference) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ivr ADD CONSTRAINT FK_7F29E7DD1E421F63 FOREIGN KEY (moh) REFERENCES musiconhold (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ivr_option ADD CONSTRAINT FK_9D6D5333B09D9E6B FOREIGN KEY (ivr_id) REFERENCES ivr (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ivr_option ADD CONSTRAINT FK_9D6D533365C11F00AEA34913 FOREIGN KEY (classname, reference) REFERENCES forward (classname, reference) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mailing ADD CONSTRAINT FK_3ED9315E90D7C22E5BB5943D FOREIGN KEY (forwardClassname, forwardReference) REFERENCES forward (classname, reference) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mailing_contact ADD CONSTRAINT FK_5DB203573931AB76 FOREIGN KEY (mailing_id) REFERENCES mailing (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE mailing_import ADD CONSTRAINT FK_4CA0FDC63931AB76 FOREIGN KEY (mailing_id) REFERENCES mailing (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_route_item ADD CONSTRAINT FK_DF331E8D3A89839C FOREIGN KEY (plan_route_id) REFERENCES plan_route (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_route_item ADD CONSTRAINT FK_DF331E8DF01282F1 FOREIGN KEY (group_number_id) REFERENCES group_number (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plan_route_item ADD CONSTRAINT FK_DF331E8D3E05B87F FOREIGN KEY (trunk_id) REFERENCES trunk (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F7198CDE5729 FOREIGN KEY (type) REFERENCES type_type (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F719C961C9B FOREIGN KEY (sendani) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F71978628D47 FOREIGN KEY (trunk) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F719E29E6BAE FOREIGN KEY (requirecalltoken) REFERENCES type_iax_require_calltoken (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F7195BBDDBBB FOREIGN KEY (encryption) REFERENCES type_iax_encryption (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F7194034A3C0 FOREIGN KEY (transfer) REFERENCES type_iax_transfer (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F719A3A0630C FOREIGN KEY (jitterbuffer) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F7193F5AF6E7 FOREIGN KEY (forcejitterbuffer) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F719B1C1B4D7 FOREIGN KEY (qualifysmoothing) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE iaxfriends ADD CONSTRAINT FK_4657F719DD7CDF4F FOREIGN KEY (adsi) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE musiconhold ADD CONSTRAINT FK_BD5D904F97CA47AB FOREIGN KEY (mode) REFERENCES type_sip_moh_mode (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA02961DABCC62 FOREIGN KEY (ringinuse) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA0296698E29BF FOREIGN KEY (setinterfacevar) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA0296BF0E1E02 FOREIGN KEY (setqueuevar) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA0296B076BC3D FOREIGN KEY (setqueueentryvar) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA0296E039DF6 FOREIGN KEY (announce_to_first_user) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA029675DFBA15 FOREIGN KEY (relative_periodic_announce) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA029642656747 FOREIGN KEY (random_periodic_announce) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA029698E57E23 FOREIGN KEY (autofill) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA0296B99C32FA FOREIGN KEY (autopause) REFERENCES type_queue_auto_pause (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA02966EE7A081 FOREIGN KEY (autopausebusy) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA0296BFDABBDF FOREIGN KEY (autopauseunavail) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA0296144645ED FOREIGN KEY (strategy) REFERENCES type_queue_strategy (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA029652579DE3 FOREIGN KEY (reportholdtime) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queues ADD CONSTRAINT FK_CFCA0296F43779C7 FOREIGN KEY (timeoutrestart) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queue_member ADD CONSTRAINT FK_4A05D0B17FFD7F63 FOREIGN KEY (queue) REFERENCES queues (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queue_member ADD CONSTRAINT FK_4A05D0B1BB861B1F FOREIGN KEY (branch) REFERENCES branch (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE queue_member ADD CONSTRAINT FK_4A05D0B18D93D649 FOREIGN KEY ("user") REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A8CDE5729 FOREIGN KEY (type) REFERENCES type_type (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A66AB212E FOREIGN KEY (transport) REFERENCES type_sip_transport (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A3D3283CE FOREIGN KEY (dtmfmode) REFERENCES type_sip_dtmf_mode (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A66C571DE FOREIGN KEY (directmedia) REFERENCES type_sip_direct_media (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A9686D0FB FOREIGN KEY (nat) REFERENCES type_sip_nat (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982AF1A0A39E FOREIGN KEY (trustrpid) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982AB920544D FOREIGN KEY (progressinband) REFERENCES type_sip_progress_in_band (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A22558EE9 FOREIGN KEY (promiscredir) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A24A832DB FOREIGN KEY (useclientcode) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982AFDC9A2D9 FOREIGN KEY (callcounter) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A21378B91 FOREIGN KEY (allowoverlap) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A2071E23B FOREIGN KEY (allowsubscribe) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A4160ACEB FOREIGN KEY (videosupport) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982AA3AA5780 FOREIGN KEY (rfc2833compensate) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A16B714ED FOREIGN KEY ("session-timers") REFERENCES type_sip_session_timers (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A5DE68FE9 FOREIGN KEY ("session-refresher") REFERENCES type_sip_session_refresher (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982AAB18E017 FOREIGN KEY (sendrpid) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A87C0D8D4 FOREIGN KEY (registertrying) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A3CCDD349 FOREIGN KEY (constantssrc) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A9A90FE26 FOREIGN KEY (usereqphone) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A6CBB95D5 FOREIGN KEY (textsupport) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A7BF8D4D9 FOREIGN KEY (faxdetect) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A75779234 FOREIGN KEY (buggymwi) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982AFDDE2612 FOREIGN KEY (sip_callingpres_values) REFERENCES type_sip_calling_pres (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982AE2235C19 FOREIGN KEY (hasvoicemail) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A4A3535ED FOREIGN KEY (subscribemwi) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982AE205704D FOREIGN KEY (autoframing) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A9FFCDCF1 FOREIGN KEY (g726nonstandard) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982AC4580138 FOREIGN KEY (ignoresdpversion) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A3ABFED67 FOREIGN KEY (allowtransfer) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982A4BAB0AB4 FOREIGN KEY (dynamic) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sippeers ADD CONSTRAINT FK_3DC2982ABF396750 FOREIGN KEY (id) REFERENCES abstract_protocol (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34DDEC97C81 FOREIGN KEY (attach) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34D71EEA338 FOREIGN KEY (deletevoicemail) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34D3A606FF1 FOREIGN KEY (saycid) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34D5999A307 FOREIGN KEY (sendvoicemail) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34D794381C6 FOREIGN KEY (review) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34DFBADBA12 FOREIGN KEY (tempgreetwarn) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34DD7A6A781 FOREIGN KEY (operator) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34D8A957868 FOREIGN KEY (envelope) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34D1B99BB46 FOREIGN KEY (forcename) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE voicemail ADD CONSTRAINT FK_DD85E34D6EBD034 FOREIGN KEY (forcegreetings) REFERENCES type_yes_no (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trunk ADD CONSTRAINT FK_78628D4758B94789 FOREIGN KEY (register_type) REFERENCES trunk_register_type (name) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trunk ADD CONSTRAINT FK_78628D476D0C27C9 FOREIGN KEY (dial_type) REFERENCES trunk_dial_type (value) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE trunk ADD CONSTRAINT FK_78628D47CCD59258 FOREIGN KEY (protocol_id) REFERENCES abstract_protocol (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E91EDB3112 FOREIGN KEY (user_access_profile_id) REFERENCES user_access_profile (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9AE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE khomp ADD CONSTRAINT FK_158F8666BF396750 FOREIGN KEY (id) REFERENCES abstract_protocol (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE oauth_access_token DROP CONSTRAINT FK_F7FA86A419EB6921');
        $this->addSql('ALTER TABLE oauth_refresh_token DROP CONSTRAINT FK_55DCF75519EB6921');
        $this->addSql('ALTER TABLE queue_member DROP CONSTRAINT FK_4A05D0B1BB861B1F');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9AE80F5DF');
        $this->addSql('ALTER TABLE branch DROP CONSTRAINT FK_BB861B1F22E7379AE9856189');
        $this->addSql('ALTER TABLE branch DROP CONSTRAINT FK_BB861B1F203B7D54EB592B47');
        $this->addSql('ALTER TABLE branch DROP CONSTRAINT FK_BB861B1F8E681B36FEB11B17');
        $this->addSql('ALTER TABLE branch DROP CONSTRAINT FK_BB861B1F65C11F00AEA34913');
        $this->addSql('ALTER TABLE incoming DROP CONSTRAINT FK_42EFA38A65C11F00AEA34913');
        $this->addSql('ALTER TABLE ivr_option DROP CONSTRAINT FK_9D6D533365C11F00AEA34913');
        $this->addSql('ALTER TABLE mailing DROP CONSTRAINT FK_3ED9315E90D7C22E5BB5943D');
        $this->addSql('ALTER TABLE plan_route_item DROP CONSTRAINT FK_DF331E8DF01282F1');
        $this->addSql('ALTER TABLE ivr_option DROP CONSTRAINT FK_9D6D5333B09D9E6B');
        $this->addSql('ALTER TABLE mailing_contact DROP CONSTRAINT FK_5DB203573931AB76');
        $this->addSql('ALTER TABLE mailing_import DROP CONSTRAINT FK_4CA0FDC63931AB76');
        $this->addSql('ALTER TABLE branch DROP CONSTRAINT FK_BB861B1F3A89839C');
        $this->addSql('ALTER TABLE plan_route_item DROP CONSTRAINT FK_DF331E8D3A89839C');
        $this->addSql('ALTER TABLE ivr DROP CONSTRAINT FK_7F29E7DD1E421F63');
        $this->addSql('ALTER TABLE queue_member DROP CONSTRAINT FK_4A05D0B17FFD7F63');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982ABF396750');
        $this->addSql('ALTER TABLE trunk DROP CONSTRAINT FK_78628D47CCD59258');
        $this->addSql('ALTER TABLE khomp DROP CONSTRAINT FK_158F8666BF396750');
        $this->addSql('ALTER TABLE branch DROP CONSTRAINT FK_BB861B1F1645FA2D');
        $this->addSql('ALTER TABLE branch DROP CONSTRAINT FK_BB861B1FF6820CFE');
        $this->addSql('ALTER TABLE plan_route_item DROP CONSTRAINT FK_DF331E8D3E05B87F');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F7195BBDDBBB');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F719E29E6BAE');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F7194034A3C0');
        $this->addSql('ALTER TABLE musiconhold DROP CONSTRAINT FK_BD5D904F97CA47AB');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA0296B99C32FA');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA0296144645ED');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982AFDDE2612');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A66C571DE');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A3D3283CE');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A9686D0FB');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982AB920544D');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A5DE68FE9');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A16B714ED');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A66AB212E');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F7198CDE5729');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A8CDE5729');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F719C961C9B');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F71978628D47');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F719A3A0630C');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F7193F5AF6E7');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F719B1C1B4D7');
        $this->addSql('ALTER TABLE iaxfriends DROP CONSTRAINT FK_4657F719DD7CDF4F');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA02961DABCC62');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA0296698E29BF');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA0296BF0E1E02');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA0296B076BC3D');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA0296E039DF6');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA029675DFBA15');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA029642656747');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA029698E57E23');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA02966EE7A081');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA0296BFDABBDF');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA029652579DE3');
        $this->addSql('ALTER TABLE queues DROP CONSTRAINT FK_CFCA0296F43779C7');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982AF1A0A39E');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A22558EE9');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A24A832DB');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982AFDC9A2D9');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A21378B91');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A2071E23B');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A4160ACEB');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982AA3AA5780');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982AAB18E017');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A87C0D8D4');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A3CCDD349');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A9A90FE26');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A6CBB95D5');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A7BF8D4D9');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A75779234');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982AE2235C19');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A4A3535ED');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982AE205704D');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A9FFCDCF1');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982AC4580138');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A3ABFED67');
        $this->addSql('ALTER TABLE sippeers DROP CONSTRAINT FK_3DC2982A4BAB0AB4');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34DDEC97C81');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34D71EEA338');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34D3A606FF1');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34D5999A307');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34D794381C6');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34DFBADBA12');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34DD7A6A781');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34D8A957868');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34D1B99BB46');
        $this->addSql('ALTER TABLE voicemail DROP CONSTRAINT FK_DD85E34D6EBD034');
        $this->addSql('ALTER TABLE oauth_access_token DROP CONSTRAINT FK_F7FA86A4A76ED395');
        $this->addSql('ALTER TABLE oauth_refresh_token DROP CONSTRAINT FK_55DCF755A76ED395');
        $this->addSql('ALTER TABLE branch DROP CONSTRAINT FK_BB861B1FA76ED395');
        $this->addSql('ALTER TABLE queue_member DROP CONSTRAINT FK_4A05D0B18D93D649');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E91EDB3112');
        $this->addSql('ALTER TABLE trunk DROP CONSTRAINT FK_78628D4758B94789');
        $this->addSql('ALTER TABLE trunk DROP CONSTRAINT FK_78628D476D0C27C9');
        $this->addSql('DROP SEQUENCE auth_client_sequence CASCADE');
        $this->addSql('DROP SEQUENCE department_seq CASCADE');
        $this->addSql('DROP SEQUENCE group_number_seq CASCADE');
        $this->addSql('DROP SEQUENCE incoming_seq CASCADE');
        $this->addSql('DROP SEQUENCE mailing_seq CASCADE');
        $this->addSql('DROP SEQUENCE mailing_contact_seq CASCADE');
        $this->addSql('DROP SEQUENCE mailing_import_seq CASCADE');
        $this->addSql('DROP SEQUENCE plan_route_seq CASCADE');
        $this->addSql('DROP SEQUENCE plan_route_item_seq CASCADE');
        $this->addSql('DROP SEQUENCE queue_members_seq CASCADE');
        $this->addSql('DROP SEQUENCE trunk_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_access_profile_seq CASCADE');
        $this->addSql('DROP TABLE oauth_access_token');
        $this->addSql('DROP TABLE oauth_client');
        $this->addSql('DROP TABLE oauth_refresh_token');
        $this->addSql('DROP TABLE branch');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE forward');
        $this->addSql('DROP TABLE group_number');
        $this->addSql('DROP TABLE incoming');
        $this->addSql('DROP TABLE ivr');
        $this->addSql('DROP TABLE ivr_option');
        $this->addSql('DROP TABLE mailing');
        $this->addSql('DROP TABLE mailing_contact');
        $this->addSql('DROP TABLE mailing_import');
        $this->addSql('DROP TABLE plan_route');
        $this->addSql('DROP TABLE plan_route_item');
        $this->addSql('DROP TABLE alembic_version');
        $this->addSql('DROP TABLE cdr');
        $this->addSql('DROP TABLE extensions');
        $this->addSql('DROP TABLE iaxfriends');
        $this->addSql('DROP TABLE meetme');
        $this->addSql('DROP TABLE musiconhold');
        $this->addSql('DROP TABLE queues');
        $this->addSql('DROP TABLE queue_log');
        $this->addSql('DROP TABLE queue_member');
        $this->addSql('DROP TABLE queue_rules');
        $this->addSql('DROP TABLE abstract_protocol');
        $this->addSql('DROP TABLE sippeers');
        $this->addSql('DROP TABLE voicemail');
        $this->addSql('DROP TABLE voicemail_messages');
        $this->addSql('DROP TABLE trunk');
        $this->addSql('DROP TABLE type_iax_encryption');
        $this->addSql('DROP TABLE type_iax_require_calltoken');
        $this->addSql('DROP TABLE type_iax_transfer');
        $this->addSql('DROP TABLE type_sip_moh_mode');
        $this->addSql('DROP TABLE type_profile_sip');
        $this->addSql('DROP TABLE type_queue_auto_pause');
        $this->addSql('DROP TABLE type_queue_strategy');
        $this->addSql('DROP TABLE type_sip_calling_pres');
        $this->addSql('DROP TABLE type_sip_direct_media');
        $this->addSql('DROP TABLE type_sip_dtmf_mode');
        $this->addSql('DROP TABLE type_sip_nat');
        $this->addSql('DROP TABLE type_sip_progress_in_band');
        $this->addSql('DROP TABLE type_sip_session_refresher');
        $this->addSql('DROP TABLE type_sip_session_timers');
        $this->addSql('DROP TABLE type_sip_transport');
        $this->addSql('DROP TABLE type_type');
        $this->addSql('DROP TABLE type_yes_no');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE user_access_profile');
        $this->addSql('DROP TABLE trunk_register_type');
        $this->addSql('DROP TABLE khomp');
        $this->addSql('DROP TABLE trunk_dial_type');
    }
}
